config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts, except: [:destroy] do
      delete :destroy, on: :collection
    end

    resources :products do
      get :who_bought, on: :member, defaults: { format: :atom }
    end

    root 'store#index', as: 'store'
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Depot
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{ class: controller.controller_name }
    #banner
      = form_tag store_path, method: :get, class: "locale" do
        = select_tag "set_locale", options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: "this.form.submit()"
        = submit_tag "submit"
        = javascript_tag "$('.locale input').hide()"
      = image_tag("logo.png")
      = @page_title || t(".title")

    #columns
      #side
        - if @cart
          = hidden_div_if(@cart.line_items.empty?, id: "cart") do
            = render @cart

        %ul
          %li= link_to t(".home"), "#"
          %li= link_to t(".questions"), "#"
          %li= link_to t(".news"), "#"
          %li= link_to t(".contact"), "#"

        - if session[:user_id]
          %ul
            %li= link_to t(".orders"), orders_path
            %li= link_to t(".products"), products_path
            %li= link_to t(".users"), users_path
          = button_to t(".logout"), logout_path, method: :delete

      #main
        = yield